export class ExportManager {
  constructor() {}

  toMarkdown(roadmap) {
    let md = `# 📋 Project Roadmap: ${roadmap.config.projectName}\n\n`;
    if (roadmap.config.projectDescription) {
      md += `> ${roadmap.config.projectDescription}\n\n`;
    }
    
    md += `**Type:** ${roadmap.config.projectType} | **Scope:** ${roadmap.config.scope} | **Team Size:** ${roadmap.config.teamSize}\n`;
    md += `**Timeline:** ${roadmap.config.startDate} → ${roadmap.config.endDate} | **Duration:** ${roadmap.stats.estimatedWeeks} weeks\n\n---\n\n`;
    
    md += `## 📊 Overview\n\n| Metric | Value |\n|--------|-------|\n`;
    md += `| Total Phases | ${roadmap.stats.totalPhases} |\n| Total Tasks | ${roadmap.stats.totalTasks} |\n`;
    md += `| Milestones | ${roadmap.stats.totalMilestones} |\n| Estimated Duration | ${roadmap.stats.estimatedWeeks} weeks |\n`;
    md += `| Critical Path Tasks | ${roadmap.criticalPath.length} |\n\n---\n\n`;
    
    md += `## 🔑 Critical Path\n\n> These tasks determine the minimum project duration. Any delay here delays the entire project.\n\n`;
    let criticalIndex = 1;
    roadmap.phases.forEach(p => {
      p.tasks.forEach(t => {
        if (t.isCriticalPath) {
          md += `${criticalIndex++}. **${t.name}** (${t.startDate} → ${t.endDate}, ${t.duration} days)\n`;
        }
      });
    });
    md += `\n---\n\n`;
    
    roadmap.phases.forEach((p, index) => {
      md += `## Phase ${index + 1}: ${p.name}\n\n### Tasks\n\n`;
      md += `| # | Task | Start | End | Duration | Dependencies | Critical? |\n|---|------|-------|-----|----------|-------------|----------|\n`;
      
      let milestones = [];
      p.tasks.forEach((t, i) => {
        const deps = t.dependencies && t.dependencies.length ? t.dependencies.join(', ') : '-';
        const crit = t.isCriticalPath ? '⚡' : '-';
        md += `| ${i+1} | ${t.name} | ${t.startDate} | ${t.endDate} | ${t.duration} days | ${deps} | ${crit} |\n`;
        if (t.isMilestone) milestones.push(t);
      });
      
      if (milestones.length > 0) {
        md += `\n### Milestones\n`;
        milestones.forEach(m => {
          md += `- 🏁 **${m.name}** — ${m.endDate}\n`;
        });
      }
      md += `\n---\n\n`;
    });
    
    md += `*Generated by Pathforge on ${new Date().toISOString().split('T')[0]}*`;
    return md;
  }

  showExportModal(roadmap, ganttContainer) {
    const overlay = document.createElement('div');
    overlay.className = 'modal-overlay';
    overlay.style.position = 'fixed';
    overlay.style.top = '0'; overlay.style.left = '0'; overlay.style.right = '0'; overlay.style.bottom = '0';
    overlay.style.background = 'rgba(0,0,0,0.5)';
    overlay.style.display = 'flex';
    overlay.style.alignItems = 'center'; overlay.style.justifyContent = 'center';
    overlay.style.zIndex = '2000';

    const modal = document.createElement('div');
    modal.className = 'modal-content';
    modal.style.background = 'var(--bg-default, #fff)';
    modal.style.padding = '20px';
    modal.style.borderRadius = '8px';
    modal.style.width = '80%';
    modal.style.maxWidth = '800px';
    modal.style.maxHeight = '90vh';
    modal.style.display = 'flex';
    modal.style.flexDirection = 'column';

    const mdContent = this.toMarkdown(roadmap);

    modal.innerHTML = `
      <div style="display: flex; justify-content: space-between; border-bottom: 1px solid #ccc; margin-bottom: 15px; padding-bottom: 10px;">
        <h2>Export Roadmap</h2>
        <div>
          <button class="btn btn-sm" id="tab-md">Markdown</button>
          <button class="btn btn-sm" id="tab-preview">Preview</button>
        </div>
      </div>
      <div id="export-body" style="flex: 1; overflow: auto; background: #f5f5f5; padding: 10px; border-radius: 4px; margin-bottom: 15px;">
        <pre><code style="white-space: pre-wrap; font-family: monospace;">${mdContent}</code></pre>
      </div>
      <div style="display: flex; gap: 10px; justify-content: flex-end;">
        <button class="btn btn-secondary" id="btn-close">Close</button>
        <button class="btn btn-primary" id="btn-copy">Copy to Clipboard</button>
        <button class="btn btn-primary" id="btn-download">Download .md</button>
      </div>
    `;

    overlay.appendChild(modal);
    document.body.appendChild(overlay);

    modal.querySelector('#btn-close').onclick = () => document.body.removeChild(overlay);
    modal.querySelector('#btn-copy').onclick = () => {
      this.copyToClipboard(mdContent);
    };
    modal.querySelector('#btn-download').onclick = () => {
      this.downloadMarkdown(roadmap);
    };

    const exportBody = modal.querySelector('#export-body');
    modal.querySelector('#tab-md').onclick = () => {
      exportBody.innerHTML = `<pre><code style="white-space: pre-wrap; font-family: monospace;">${mdContent}</code></pre>`;
    };
    modal.querySelector('#tab-preview').onclick = () => {
      exportBody.innerHTML = `<div style="padding: 10px;">${this.renderBasicHTML(mdContent)}</div>`;
    };
  }

  renderBasicHTML(md) {
    return md
      .replace(/^# (.*$)/gim, '<h1>$1</h1>')
      .replace(/^## (.*$)/gim, '<h2>$1</h2>')
      .replace(/^### (.*$)/gim, '<h3>$1</h3>')
      .replace(/^> (.*$)/gim, '<blockquote>$1</blockquote>')
      .replace(/\\*\\*(.*)\\*\\*/gim, '<strong>$1</strong>')
      .replace(/^---$/gim, '<hr>')
      .replace(/\\n/g, '<br>');
  }

  copyToClipboard(text) {
    navigator.clipboard.writeText(text).then(() => {
      this.showToast('Copied to clipboard!');
    });
  }

  downloadMarkdown(roadmap) {
    const md = this.toMarkdown(roadmap);
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${roadmap.config.projectName.replace(/\\s+/g, '-')}-roadmap.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  exportPNG(ganttContainer, projectName) {
    this.showToast('PNG export not fully implemented in this stub, but would serialize SVG to Canvas here.');
  }

  showToast(msg) {
    const toast = document.createElement('div');
    toast.className = 'toast toast-success';
    toast.textContent = msg;
    toast.style.position = 'fixed';
    toast.style.bottom = '20px';
    toast.style.left = '50%';
    toast.style.transform = 'translateX(-50%)';
    toast.style.background = '#10b981';
    toast.style.color = 'white';
    toast.style.padding = '10px 20px';
    toast.style.borderRadius = '20px';
    toast.style.zIndex = '3000';
    toast.style.transition = 'opacity 0.5s';
    
    document.body.appendChild(toast);
    
    setTimeout(() => {
      toast.style.opacity = '0';
      setTimeout(() => document.body.removeChild(toast), 500);
    }, 2000);
  }
}
